---
title: Matt Spradley
timezone: America/Denver
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: false
    share: true
subtitle: Enjoying the journey
name: Matt Spradley
description: A personal site hosted on GitHub Pages.
url: https://mattspradley.com
baseurl: ''
include:
  - CNAME
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: air
#search: true
#show_excerpts: true
show_teasers: true
author:
  name: Matt Spradley
  avatar: "/assets/images/profile.jpg"
  bio: 'Startup CTO and platform strategist who has scaled engineering organizations
    from startup to enterprise. Leader in SaaS, IoT, and healthtech, and a cloud expert
    trying to keep up in the fast-moving AI/ML landscape.
'
  location: Fort Collins, Colorado
  links:
  - label: GitHub
    icon: fab fa-github
    url: https://github.com/mattspradley
  - label: LinkedIn
    icon: fab fa-linkedin
    url: https://linkedin.com/in/mattspradley
comments:
  provider: 'false'
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-Z9HXKLWW4R"

plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-include-cache
