---
title: Matt Spradley
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: false
    share: true
subtitle: A work in progress
name: Matt Spradley
description: A personal site hosted on GitHub Pages.
url: https://mattspradley.github.io
baseurl: ''
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: default
author:
  name: Matt Spradley
  avatar: "/assets/images/profile.jpg"
  bio: Short bio here.
  location: City, Country
  links:
  - label: GitHub
    icon: fab fa-github
    url: https://github.com/mattspradley
  - label: LinkedIn
    icon: fab fa-linkedin
    url: https://linkedin.com/in/mattspradley
main:
- title: Home
  url: "/"
- title: About
  url: "/about/"
- title: Blog
  url: "/blog/"
- title: Contact
  url: "/contact/"
paginate: 5
paginate_path: "/page:num/"
search: true
comments:
  provider: 'false'
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-include-cache
